CREATE TABLE STUDENT(
ID INT(2) PRIMARY KEY,
FIRST_NAME VARCHAR(30),
SECOND_NAME VARCHAR(30),
ADDRESS VARCHAR(70),
PHONE_NUMBER BIGINT(10),
DATE_OF_BIRTH DATETIME,
GENDER CHAR(1) CHECK GENDER IN ('M','F'),
BLOOD_GROUP VARCHAR(3),
EMAIL_ID VARCHAR(50),
FATHERS_NAME VARCHAR(50),
MOTHERS_NAME VARCHAR(50),
GURDIANS_NAME VARCHAR(50),
CID INT(3),
PWD VARCHAR(1)
);